language: node_js
node_js:
  - node
dist: bionic
sudo: required

notifications:
  email:
    receipients:
    - vinc3nt86@gmail.com
    on_success: always
    on_failure: never
  slack: csf-2019:ONgoUzwpaNRcrOZfcymFsagb
    on_success: always
    on_failure: always
    
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - ng build --prod --base-href https://vincentgoay.github.io/weather-app-1/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/weather-app
  on:
    branch: master
