language: node_js
node_js:
  - node
dist: bionic
sudo: required
branches:
  only:
    - routing
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run test-headless
  - ng build --prod --base-href https://vincentgoay.github.io/weather-app-1/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/weather-app
  on:
    branch: worksheet1
